# Generated by Django 4.2 on 2023-04-19 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=100, unique=True)),
                ('phone', models.CharField(default='', max_length=12)),
                ('role', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
                ('schoolId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.schools')),
            ],
        ),
    ]
